# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/params/param.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.common import common_pb2 as proto_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/params/param.proto',
  package='param.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18proto/params/param.proto\x12\x0bparam.proto\x1a\x19proto/common/common.proto\"9\n\x06Params\x12/\n\x0c\x63ommon_filed\x18\x01 \x01(\x0b\x32\x19.common.proto.CommonField')
  ,
  dependencies=[proto_dot_common_dot_common__pb2.DESCRIPTOR,])




_PARAMS = _descriptor.Descriptor(
  name='Params',
  full_name='param.proto.Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common_filed', full_name='param.proto.Params.common_filed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=125,
)

_PARAMS.fields_by_name['common_filed'].message_type = proto_dot_common_dot_common__pb2._COMMONFIELD
DESCRIPTOR.message_types_by_name['Params'] = _PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Params = _reflection.GeneratedProtocolMessageType('Params', (_message.Message,), dict(
  DESCRIPTOR = _PARAMS,
  __module__ = 'proto.params.param_pb2'
  # @@protoc_insertion_point(class_scope:param.proto.Params)
  ))
_sym_db.RegisterMessage(Params)


# @@protoc_insertion_point(module_scope)
