apiVersion: argoproj.io/v1alpha1
kind: Workflow   # Argo Workflow CRD 资源类型
metadata:
  generateName: sidecar-nginx-  # Workflow 配置名称
spec:
  entrypoint: sidecar-nginx-example  # 解析 sidecar-nginx-example 模板
  templates:
  - name: sidecar-nginx-example # 模板名称 (和 entrypoint 保持一致)
    container:
      image: appropriate/curl # 带有curl命令的 Alpine 容器
      command: [sh, -c]
      args: ["until `curl -G 'hettp:/127.0.0.1/' >& /tmp/out`; do echo sleep && sleep 1; done && cat /tmp/out"]
    sidecars:
    - name: nginx
      image: nginx:1.13  # nginx 容器
