# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/common/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/common/common.proto',
  package='common.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19proto/common/common.proto\x12\x0c\x63ommon.proto\"Y\n\x0b\x43ommonField\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.common.proto.TopicType\x12#\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x15.common.proto.Payload\"\x18\n\x04Mock\x12\x10\n\x08mock_int\x18\x01 \x01(\x05\"u\n\x07Payload\x12\x0f\n\x07val_int\x18\x01 \x01(\x05\x12\x0f\n\x07val_str\x18\x02 \x01(\t\x12#\n\x07val_msg\x18\x03 \x01(\x0b\x32\x12.common.proto.Mock\x12#\n\x07val_arr\x18\x04 \x03(\x0b\x32\x12.common.proto.Mock*5\n\tTopicType\x12\x12\n\x0eTOPIC_PLANNING\x10\x01\x12\x14\n\x10TOPIC_PERCEPTION\x10\x02')
)

_TOPICTYPE = _descriptor.EnumDescriptor(
  name='TopicType',
  full_name='common.proto.TopicType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TOPIC_PLANNING', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOPIC_PERCEPTION', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=279,
  serialized_end=332,
)
_sym_db.RegisterEnumDescriptor(_TOPICTYPE)

TopicType = enum_type_wrapper.EnumTypeWrapper(_TOPICTYPE)
TOPIC_PLANNING = 1
TOPIC_PERCEPTION = 2



_COMMONFIELD = _descriptor.Descriptor(
  name='CommonField',
  full_name='common.proto.CommonField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='common.proto.CommonField.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='common.proto.CommonField.body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=132,
)


_MOCK = _descriptor.Descriptor(
  name='Mock',
  full_name='common.proto.Mock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mock_int', full_name='common.proto.Mock.mock_int', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=158,
)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='common.proto.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val_int', full_name='common.proto.Payload.val_int', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_str', full_name='common.proto.Payload.val_str', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_msg', full_name='common.proto.Payload.val_msg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='val_arr', full_name='common.proto.Payload.val_arr', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=277,
)

_COMMONFIELD.fields_by_name['type'].enum_type = _TOPICTYPE
_COMMONFIELD.fields_by_name['body'].message_type = _PAYLOAD
_PAYLOAD.fields_by_name['val_msg'].message_type = _MOCK
_PAYLOAD.fields_by_name['val_arr'].message_type = _MOCK
DESCRIPTOR.message_types_by_name['CommonField'] = _COMMONFIELD
DESCRIPTOR.message_types_by_name['Mock'] = _MOCK
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.enum_types_by_name['TopicType'] = _TOPICTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonField = _reflection.GeneratedProtocolMessageType('CommonField', (_message.Message,), dict(
  DESCRIPTOR = _COMMONFIELD,
  __module__ = 'proto.common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.CommonField)
  ))
_sym_db.RegisterMessage(CommonField)

Mock = _reflection.GeneratedProtocolMessageType('Mock', (_message.Message,), dict(
  DESCRIPTOR = _MOCK,
  __module__ = 'proto.common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.Mock)
  ))
_sym_db.RegisterMessage(Mock)

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'proto.common.common_pb2'
  # @@protoc_insertion_point(class_scope:common.proto.Payload)
  ))
_sym_db.RegisterMessage(Payload)


# @@protoc_insertion_point(module_scope)
