# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/desc/desc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/desc/desc.proto',
  package='desc.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x15proto/desc/desc.proto\x12\ndesc.proto\"D\n\tDescProto\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\x0c\x12)\n\ndependency\x18\x02 \x03(\x0b\x32\x15.desc.proto.DescProto')
)




_DESCPROTO = _descriptor.Descriptor(
  name='DescProto',
  full_name='desc.proto.DescProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='desc', full_name='desc.proto.DescProto.desc', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dependency', full_name='desc.proto.DescProto.dependency', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=105,
)

_DESCPROTO.fields_by_name['dependency'].message_type = _DESCPROTO
DESCRIPTOR.message_types_by_name['DescProto'] = _DESCPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DescProto = _reflection.GeneratedProtocolMessageType('DescProto', (_message.Message,), dict(
  DESCRIPTOR = _DESCPROTO,
  __module__ = 'proto.desc.desc_pb2'
  # @@protoc_insertion_point(class_scope:desc.proto.DescProto)
  ))
_sym_db.RegisterMessage(DescProto)


# @@protoc_insertion_point(module_scope)
